server:
 servlet:
    context-path: /pomodoro/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://lucascorreia:i8ueMSSM86vm5HDc@pomodoro.goxbnpc.mongodb.net/pomodoro?retryWrites=true&w=majority}
      auto-index-creation: true

